[package]
name = "alphanet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Reth AlphaNet is a testnet OP Stack rollup aimed at enabling experimentation of bleeding edge Ethereum Research."
default-run = "alphanet"

[lints]
workspace = true

[dependencies]
alloy-signer-local.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alphanet-node.workspace = true
alphanet-wallet.workspace = true
eyre.workspace = true
tracing.workspace = true
reth-cli-util.workspace = true
reth-node-builder.workspace = true
reth-optimism-node.workspace = true
reth-optimism-cli.workspace = true
reth-optimism-rpc.workspace = true
reth-provider.workspace = true
reth-exex.workspace = true
futures = "0.3"
clap = { workspace = true, features = ["derive"] }
async-trait = "0.1"
jsonrpsee = { version = "0.24", features = ["server", "macros"] }
tokio-stream = "0.1"
tokio = { workspace = true, features = [
    "sync",
    "macros",
    "time",
    "rt-multi-thread",
] }
serde.workspace = true
serde_json.workspace = true

[features]
default = ["jemalloc"]

asm-keccak = ["reth-optimism-cli/asm-keccak"]

jemalloc = ["reth-cli-util/jemalloc"]
jemalloc-prof = ["jemalloc", "reth-cli-util/jemalloc-prof"]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

[[bin]]
name = "alphanet"
path = "src/main.rs"
